---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld-hostname
  replicas: 10
  template:
    metadata:
      labels:
        app: helloworld-hostname
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: helloworld-hostname
        image: strm/helloworld-http
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld-hostname
  ports:
    - port: 80


