---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-dev-deployment
spec:
  selector:
    matchLabels:
      app: nginx-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nginxpod
#        image: f5devcentral/f5-hello-world:develop
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-dev
  ports:
    - port: 80


